apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigpayloadtest
  labels:
    app: bigpayloadtest
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bigpayloadtest
  selector:
    matchLabels:
      app: bigpayloadtest
  template:
    metadata:
      labels:
        app: bigpayloadtest
    spec:
      containers:
      - name: bigpayloadtest
        image: registry.cn-beijing.aliyuncs.com/aliyun-asm/bigpayloadtest:v0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bigpayloadtest
  name: bigpayloadtest
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: bigpayloadtest
  sessionAffinity: None

